# Generated by Django 2.0.3 on 2018-04-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
