# Generated by Django 2.0.3 on 2018-04-09 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stm_comm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stm_comm.Item')),
            ],
            bases=('stm_comm.item',),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TempItem',
            fields=[
                ('actualitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stm_comm.ActualItem')),
            ],
            bases=('stm_comm.actualitem',),
        ),
    ]
