# Generated by Django 2.0.3 on 2018-04-25 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stm_comm', '0002_auto_20180423_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=0, max_length=60)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stm_comm.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tempitem',
            name='value',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
