# Generated by Django 2.0.3 on 2018-04-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stm_comm', '0002_auto_20180409_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='device',
        ),
        migrations.AddField(
            model_name='tempitem',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stm_comm.Device'),
            preserve_default=False,
        ),
    ]
