# Generated by Django 2.0.3 on 2018-05-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stm_comm', '0003_auto_20180425_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalsitem',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tempitem',
            name='time',
        ),
    ]
