# Generated by Django 2.0.3 on 2018-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_comm', '0004_auto_20180522_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalsitem',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempitem',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
