# Generated by Django 2.0.3 on 2018-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_comm', '0006_auto_20180716_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
